spring:
  cloud:
    config:
      enabled: false
  application:
    name: book-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/author-service
      database: book_service
      username:
      password:
server:
  port: 8200
logging:
  level:
    #    root: WARN
    org:
      mongodb:
        driver: DEBUG
      springframework:
        #        web: WARN
        data:
          core:
            MongoTemplate: DEBUG
            MongoOperations: DEBUG
  pattern:
    console: "%msg%n"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/