spring:
  cloud:
   config:
     enabled: false
  application:
    name: author-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/author-service
      database: author_service
      username:
      password:
server:
  port: 8100
logging:
  level:
    #    root: WARN
    org:
      mongodb:
        driver: DEBUG
      springframework:
        #        web: WARN
        data:
          core:
            MongoTemplate: DEBUG
            MongoOperations: DEBUG
  pattern:
    console: "%msg%n"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


springdoc:
  show-actuator: true
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: swagger-ui.html



management:
  endpoints:
    web:
      exposure:
        include: "health,info,openapi,swagger-ui" # http://localhost:8100/actuator/
  server:
     port: 8101


  health:
    mongo:
     ping:
       enabled: true?



  endpoint:
      health:
         show-details: always