spring:
  cloud:
   config:
     enabled: false
  application:
    name: author-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/author-service
      database: author_service
      username:
      password:
server:
  port: 9100
logging:
  level:
    #    root: WARN
    org:
      mongodb:
        driver: DEBUG
      springframework:
        #        web: WARN
        data:
          core:
            MongoTemplate: DEBUG
            MongoOperations: DEBUG
  pattern:
    console: "%msg%n"